### ISSUE TITLE
PRACTICA

### ISSUE THREAD

**Issue by Alberto796** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Alberto796#1]
[PRACTICA joaquin alberto gonzalez romero[1].pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Alberto796/files/12591333/PRACTICA.joaquin.alberto.gonzalez.romero.1.pdf)

**Comment by 00Asaf00** [comment]
Portada: 100%
Procedimiento: 60%
Figuras-Ilustraciones-Fotografías: 70% (las incluye pero no son muy intuitivas)
Resultados y conclusiones: 60% (Muestra los procedimientos durante el ejercicio pero no al final)

Calificación: 0.2*72.5 = 15

**Comment by josealfredo79** [comment]
Revisado...
